### ISSUE TITLE
New request to visualize point cloud with x, y, z, r, g, b

### ISSUE THREAD

**Issue by hduonggithub** [HectorPeeters/opengl_premake_boilerplate#1]
Hi @HectorPeeters 

Thanks for the code and instruction. I was able to make it in a second. This is very very helpful to overcome a lot of issues when building from scratch.

My new request if you can make another tutorial or provide a guide to display 3D point cloud (x,y,z,r,g,b) into the current project. Thanks

**Comment by HectorPeeters** [comment]
I think this would be an excellent practice exercise if you want to learn OpenGL! It shouldn't be that difficult and if you get stuck there are always the tutorials on www.learnopengl.com if you get stuck.

Thanks for the kind feedback and good luck on your point cloud adventures!
