### ISSUE TITLE
Doesn't seem to work with the latest version of GLFW and ImGui

### ISSUE THREAD

**Issue by cogilv25** [HectorPeeters/opengl_premake_boilerplate#2]
Some files moved around in ImGui which was easy to fix, however GLFW gives a lot of unresolved external symbol errors which I haven't been able to easily figure out and don't have the time to mess around with at the moment.

Should mention this is on a windows 10 pc in case it works fine on other platforms!

![image](https://user-images.githubusercontent.com/4955634/198416320-72b97719-f225-4396-95a2-144aa9181688.png)

**Comment by HectorPeeters** [comment]
Hey Calum,

Thanks for pointing out this problem. I haven't been actively working on this project for a while now, so I missed your issue and pr. If you want, you can reopen the pr so I can merge it!

**Comment by cogilv25** [comment]
Hi,

Sorry for the slow reply! I have remade the pull request, however, I'm not sure if I have linked it to the issue properly! I just updated it originally while I was having a look at how it worked! Might as well share things like that and help anyone who comes across it in my opinion!

Thank you for taking the time!
Calum

**Comment by HectorPeeters** [comment]
Wonderful!
I'll test it out on Linux right now. As for linking the issue, just adding `Closes #2` to the description instead of the title should do the job.

Thanks for fixing this issue!
Hector
